* Интро
Шпаргалка по теории графов.

* Теория графов.

** Зачем нужны графы

Графы строят, чтоб отобразить отношения между элементами во множествах.

** Определение

Пусть V – (непустое) множество вершин, элементы v ∈ V – вершины. Граф G =
G(V) с множеством вершин V есть некоторое cемейство пар вида: e = (a, b),
где a,b∈ V, указывающих, какие вершины остаются соединёнными. Каждая пара
e = (a, b) - ребро графа. Множество U - множество рёбер графа. Вершины
a и b – концевые точки ребра.

Перевод на русский:
Есть некоторое мнодество вершин V, где каждая вершина v принадлежит
множеству V. Граф, который мы назовем G, будем обозначать как G(V) -
т.е. этот граф от множества вершин V - это некоторое некоторое множество
пар вида  e = (a, b), где а и b принадлежат к множеству V и указывают,
какие вершины оказываются соединенными. Т.е. граф мы можем выразить как
множество пар ребер, где вершины принадлежат к одному множеству и
являются коневыми точками ребра.

** Виды вершин и ребер графа

*** Дуга

Это направленное ребро - т.е. по нему можно двигаться в одном направлении

*** Звено

Это ненапрвленное ребро.

*** Петля

Это когда вершина соединена сама с собой ребром. При этом петля всегда
добавляет 2 к степени вершины.

*** Кратные ребра

Это ребра, соединяющие одну и ту де пару вершины между собой. Т.е. от
вершины а к вершине b ведет несколько ребер.

*** Голая вершина

Это вершина, которая не инцидентна -никакому ребру графа -  т.е. не лежит
на пути никакого ребра, не соединена с графом ниаким образом.

*** Изолированная вершина

Это вершина, инцидентная одной или нескольким петлям - т.е. через нее
проходят одна или несколько петель.

*** Смежные вершины

Это вершины, которые содеиняет хотя бы одно ребро.

** Виды графов
*** Простой граф

Это граф, вершины которого соединены тмаксимум 1 ребром друг с другом,
некоторые вершины могут быть не соединенными ни с одной другой.
В таком графе не будет мультиребер или петель.

*** Ориентированный граф

Ориентированный граф - это направленный граф, т.е. когда от вершины к
вершине можно двигаться только в каком-то одном направлении. Например,
бинарное дерево - это направленный ациклический граф.

В ориентированном графе ращличают входящую и исходящую степень вершин.
Ориентированный граф называется простым, если он не имеет петель и ребер
с одинаковой упорядоченной парой вершин - т.е. он не должен иметь петельи
кратнх ребер, направление у которых было бы в одну сторону.

Т.е. если в графе есть вершина 2 и 3, и из вершины 2 идет два ребра в
вершину 3, то граф уже не простой. А еслиу нас все те же вершины, но одно
ребро идет из вершины 2 в 3, а другое идет из 3 в 2, то граф уже
простой.

**** Понятие смежных вершин в ориентированных графах
Есть две вершины: x y. Мы говорим, что вершина y является смежной с
вершиной x в том случае, если есть ребро, исходящее из вершины x в
вершину y.

Т.е x -> y - значит, вершина y смежная вершине x. Но при этом вершина x
не будет смежной для вершины y (!).

*** Неориентированный граф

Неоринетированный граф - это граф, по которому можно
ходить в любом направлении. Поэтому степень у вершины будет одна.

**** Понятие смежных вершин в неориентированных графах.

Две вершины. Они являются смежными друг для друга, если соединены
ребром.

*** Смешанный граф

Есть 3 вида ребер: дуги, петли и звенья. Смешаный граф - это граф, в
котором есть хотя бы 2 из 3 видов ребер.

*** Мультиграф

Это граф, содержащий кратные ребра, но не содержащий петель.

*** Полный граф

Граф называют полным, если он содержит в себе все возможные для
определенного типа графа ребра при неизвенном количестве вершин. Т.е. в
графе максимальное кол-во возможныхдля него ребер.

*** Двудольный граф

Двудольный граф или биграф - это граф, множество вершин которого можно
разбить на  две части (два подмножества) таким образом , что ребра графа
могут соединять только вершину из позмножества А и вершину из
подмножества В, но ни в коем случае не соединяет вершины из одного
подмножества.

*** Эйлеров граф

Эйлеровым графом называется граф, в котором можно обойти все
вершины и при этом пройти одно ребро только один раз. В нём каждая
вершина должна иметь только чётное число рёбер.

*** Регулярный граф

Это граф, все вершины которого имеют одинаковую степень - т.е. из каждой
вершины исходит одинаковое кол-во ребер.

*** Гамильтонов граф

Гамильтонов граф - это такой граф, в котором можно обойти все вершины и
каждая вершина при обходе повторяется лишь один раз. Отличие от
эйлерового в том, что в эйлеровом графе каждая вершина должна иметь
четное кол-во ребер.


** Матрица инцидентности

Одна из форм представления графа, в которой указываются связи между
инцидентными элементами графа: ребро (дуга) и вершина. Столбцы матрицы
соответствуют ребрам, строки — вершинам. Ненулевое значение в ячейке
матрицы указывает связь между вершиной и ребром (их инцидентность).

** Матрица смежности

Это матрица размером N x N, где N - это кол-во вершин в графе. В матрице
есть строки и слобцы. Строки обозначим как i, а столбцы как j. Элемент,
находящийся на пересечении строки и стобца обозначает кол-во ребер,
исходщих из вершины i и входящих в вершину j.

Т.е. предаставим себе, что у нас есть 4 вершины в графе. Это значит, что
у нас будет матрица 4 на 4. Где i - это какая-то из строк матрицы (их будет 4) - а
j - это какой-то из столбцов матрицы.
Элемент, который будет находиться на пересечении j1 и i1 будет обозначаль
кол-во ребер, исходящих из вершины i в вершину j.

В случае затыка смотри сюда
https://www.youtube.com/watch?v=TLV2akXrAXE

*** Матрица смежности для простого неориентированного графа

Будет состоять только из нулей и единиц - потому что у нас две вершины
могут быть соединены максимум 1 ребром.

** Первая теорема теории графов или лемма о рукопожатиях

Сумма степеней вершин графа равняется кол-ву ребер графа, умноженному
на 2.

Доказательство:
Любое ребро дает вклад равный 2 в суммарную степень вершин графа. Поэтому
и получается, что сумма степеней вершин графа = удвоенному кол-во ребер
графа.

Из этого следует, что кол-во вершин с нечетной степенью всегда
четно. В другом случае граф просто не существует.

Эта теорема известна как лемма о рукопожатиях, согласно которой кол-во
людей, которые нечетное кол-во раз пожали руки другим людям, обязательно
будет четным.

** Задача

В группе имеется девять студентов. Каждый из них послал по сообщению
каким-то трем другим студентам. Возможна ли ситуация, при которой каждый
студент получит сообщения от тех же трех студентов, кому он послал свои сообщения?

Для ответа используйте первую теорему теории графов.

*** Решение

Представляем себе граф, в котором 9 вершин - 9 студентов. Если каждый
студент послал по 3 сообщения, то получается, что у каждой вершины будет
минимум 3 ребра, т.е. миимум степень вершины = 3. Вопрос звучит как
"возможно ли, что студент получит сообщения от тех же 3х студентов, кому
он послал сообщения" поэтому мы будем считать, что граф у нас не
направленный - по одному и тому же ребру (связи) оба студента могут
обмениваться сообщениями.

Поэтому считаем, что степень каждой вершины = 3. Это значит, что
суммарная степень графа у нас 3 * 9 = 27. Раз сумма степеней всех вершин
= 27, то по первой теореме у нас должно быть число ребер, умножив которое
на 2 мы получим 27. Но такого целого числа нет.
