* Интро
Шпаргалка по комбинаторике

Комбинаторика изучает сколькими способами можно перестаивть элементы в
множестве согласно заданному усло

* Множества

** Множество

Это набор некоторых элементов, объединеннх по какому-то
признаку. Элементы должны быть разными - т.е. если у нас можество чисел
от 1 до n, то в множестве не может два раза встретиться число 3,
например.

** Мощность множества

Это кол-во элементов в множестве

** Операции над множествами
*** Объединение

Есть множества А и В, их объединение - это множество, которе включает в
себя все элементы из А и В.

*** Пересечение

Берем 2 множества. Их пересечение - это множество, образованное
элементами, которые являются общими для этих множеств.

*** Разность

Есть 2 множества. Разность множества А минус B - это все элементы множества А,
которые не принадлежат множеству В.

*** Дополнение

Есть множество А, которое является частью более крупного множества
В. Дполонение множества А - это все элементы, которые входят в множество
В, но при этом не являются множеством А.

Например, есть кучка с разноцветными камушками. Среди них есть только
красные камушки - множество А. А все остальные камни из кучки - это
дополнение к множеству А, потому что они все еще камушки, но при этом не
красные.

*** Покраытие множества семейством множеств

Предположим, у нас есть множества Х1, X2 .... Xk  и есть
множество X. Мы говорим, что множества Х1, X2 .... Xk покрывают множество
X, если объединение всех этих множеств дает множество Х.

Предположим, есть множество камушков и множества красных, синих и зеленых
камушков. Мы говорим, что множества красных, синих и зеленых камушков
покрывет можество камушков, если объединение этих множеств даст все
множество камушков.

*** Разбиение

Предположим, у нас есть множества Х1, X2 .... Xk  и есть
множество X. Мы говорим, что множества Х1, X2 .... Xk - это разбиение
множества Х, если:

- любое мноежство Х-итое не пустое
- любые Х-итые множества попарно не пересекаются
- все Х-итые множества образуют покрытие для множества Х

Все Х-итые называются блоками разбиения в этом случае.

Разбиение бывает упорядоченным  - это когда все Х-итые обяазтельно должны
быть в каком-то порядке.

*** Разделение множества

Это упорядоченное разбиение, где могут быть Х-итые пустые множества. Все
остальные определения разбиения сохраняются.

*** Декартово произведение множеств

Есть 2 множества А и В. Их декртово произведение - это множество
~упорядоченных~ пар (a b), где а принадлежит множеству А, а b принадлежит
множеству В. Множеств может быть больше двух, например, есть множества
Х1, X2 .... Xk, тогда декартово произведение этих множеств будет
упорядоченной последовательностью (x1, x2, ...xk).
Если эти множества совпадают, то мы просто имеетм X^k. Т.е. это будет
последовательность (x1, x2, ...xk), где все x-итые принадлежат множеству X.
Тогда X^k - это декартова степень.

*** K-мульти множество

Оно прочно связано с понятием декартовой степени. Фактически, это те же
последовательности (x1, x2, ...xk), где все x-итые принадлежат множеству
X, только ~неупорядоченные~. И тогда  (x1, x2, ...xk) - это
к-мультимножество над множеством Х.

Предположим, есть множество Х, состоящее из элементов х и y. И допустим
мы говорим, что мы должны составить все возможные 3-мультимножества над
множеством Х - т.е. в "подмножестве" может быть толкьо 3 элемента.

Получается (x x x) (x y y ) (x x y) ( y y y ) - перестановки типа ( y y
x) мы не учитываем, потому что от этой перестановки ничего не меняется.



** Законы д'Моргана

Есть множество X и есть 2 подмножества этого множества: А и В. Допустим,
мы хотим найти пересечение дополнений этих множеств. Законы д'Моргана
гласят, что пересечение дополнений этих множеств - это объединение
дополнений этих множеств, и наоборот.

* Основные правила перечислительной комбинаторики
** Правило суммы

Предположим, есть два непересекающихся множества. Сумма этих множеств - это их
объединение, т.е. все элементы одного и другого множества.

Предположим, что у нас разбиение некоторого множества на
блоки. Объединение - т.е. сумма элементов всех блоков - должна быть равна
исходному множеству.

Допустим, в группе 50 студентов, которых мы разбиваем на 2 множеств по
половому признаку. У нас получается 2 множества: мальчики - 30 чел, и
девочке - 20 чел. Тогда объединение этих двух множеств даст нам исходное
множество студентов.

** Правило произведения
Пусть объект a можно выбрать m способами, после чего объект b можно
выбрать n способами. Тогда упорядоченную пару (a, b) можно выбрать mn
способами; иными словами, существует mn различных упорядоченных пар (a, b).

Предположим, есть 3 группы студентов: в первой - 15 чел, во второй - 20
чел и в 3 - 10 чел. Надо посчитать, сколькими способами можно выбрать
тройку студентов так, чтоб в ней были представители из всех 3х групп.

Получается, у нас 3 объекта: a, b, c. Согласно правилу произведения у нас
есть 15 * 20 * 10 способов составить тройки так, чтоб в них было по
человеку из каждой группы.

*** Задача
Сколько существует целых чисел между 0 и 999, содержащих ровно одну цифру
7?

**** Рассуждение
Рассуждаем. Можно было бы вручную выписать все числа, но можно сойти с
ума. Поэтому поступаем проще. В каждом десятке есть ровно 1 число,
содержащее цифру 7: 7, 17, 27 и т.д. Исключением является числа от 70 до
79, где каждое число содержит минимум 1 цифу 7. Следовательно, в
промежутке от 70 до 79 у нас будет 9 чисел, содержищих ровно оддну
семерку - число 77 не подходит.

Таким образом, в каждой сотне у нас будет 9 + 9 чисел, содержащих минимум
1 семерку. У нас есть 10 сотен (если считать сотню от 0 до 99) и только 9
из них попадут под это правило - исключением является диапазон от 700
до 799. Получается, что у нас (9 + 9) * 9 чисел + надо посчитать, сколько
чисел от 700 до 799 нам подходит под условие.

В диапазоне от 700 до 799 в каждом числе будет минимум 1
семерка. Следовательно, нам нужно исклчить все числа, где их больше
одной: исключаем все числа от 770 до 779 - это 10 чисел. Так же исключем
числа 707, 717, 727, 737, 747, 757, 767, 787, 797 - это еще 9
чисел. Таким образом из сотни надо убрать 19 чисел, остается 81.

Итого кол-во чисел от 0 до 999, содержащих семерку высчитывается как:
(9 + 9) * 9 + 81 = 225


*** Задача
Сколькими способами можно выбрать на шахматной доске два поля, не лежащие
на одной горизонтали или вертикали?

**** Рассуждение
Доска - это 8*8 клеток. Представим себе 2 множества - буквы и цифры, по 8
элементов в каждом.

Если бы вопрос двучал как "сколькими способами можно выбрать любые два
поля" ответ был бы как 64 * 63 - потому что при выборе первого поля у
меня 64 возмодные комбинации, а при выборе второго поля их становится
63 - одна клетка занята первым выбором.

Но в случае с нашей задачей проще думатьв терминах вертикалей и
горизонталей. На стандартной доске будет 8 горизонталей и 8 вертикалей.
Первый выбор я могу сделать по-прежнему 64 способами - мне доступны все
клетки на всех вертикалях и горизонталях. Но как только я это сделаю, у
меня останется только 7 свободных вертикалей и 7 свободных горизонталей,
куда я могу поставить свою вторую фигуру - потому что 1 вертикаль и 1
горизонталь всегда пересекаются. Следовательно, сделав выбор в первый раз
я гарантированно займу 1 горизонталь и 1 вертикаль сразу.

Таким образом есть (8 * 8) * (7 * 7) = 3136 спосоов расставить 2 фигуры
так, чтоб они не пересекались ни по горизонтали, ни по вертикали. Но
фишка в том, что такой подсчет дает повторяюющиеся варианты - типа, пешка
стоит на а1, конь стоит на b2 или наоборот, пешка стоит на b2, а конь
стоитна a1. И это по факту один и тот же способ. Поэтому кол-во способов
следует поделить на 2. Таким образом финальный ответ 1568 способов.

*** Задача
Сколько чисел в диапазоне от 0 до 999 999 не содержат двух рядом стоящих
одинаковых цифр?

**** Рассуждение
Сначала я думала посчитать все числа, в которых есть повторяющиеся
соседние цифры и полученное кол-во вычесть из всего множестве чисел. Но
это слишком муторно и проще посчитать прямо как в условии задачи.

Разделяем все числа на блоки:
1. a
2. ab
3. abc
4. a bcd
5. ab cde
6. abc def
, где все цифры от a до f - разные.

- В множестве 1 будет 10 способов выбрать число - потому что от 0 до 9.
- В 2 множестве будет (9 * 9) способов выбрать числа a/b так, чтоб они не
  повторялись. Вместо числа "a" может стоять только число от 1 до 9. А
  вместо "b" числа от 0 до 9 - казалось бы, 10 способов - но только кроме
  той же цифры, что стоит вместо "а".
- В третьем множестве получается (9 * 9 * 9) - потому что, опять же, "а"
  можно выбрать только 9 способами, b - десятью спсобами, но цифра не
  должна повторяться с "а", с - по аналогии с b девятью способами. Потому
  что в задаче сказано, что одинаковые цифры не должны стоять рядом - а
  не то, что число не должно соедржать одинаковых чисел в принципе.

Ну и т.д.
Получается (+ 10 (expt 9 2) (expt 9 3) (expt 9 4) (expt 9 5) (expt 9 6)) =
597871

** Принцип включения исключения
Допустим, у нас есть множество А, которе является частью множества Х.
Нам нужно вычислить, сколько элементов в дополнении к множеству А -
т.е. сколько элементов не являются частью множества А, но являются частью
множества Х.

Для этого нао из Х вычесть А - так мы полчим оставшиеся элементы
множества Х, т.е. дополнение.

Теперь предположим, что есть пересекающиеся множества А и В, которые
являются частью множества Х. И мы хотим вычислить кол-во элементов в
дополнении для А и В - т.е. кол-во всех элементов, которые не входят в А
или В, но при этом входят в Х.

Для этого нужно из Х вычесть все элементы из А и все элементы из В, а
затем ~сложить~ c полученной разностью кол-во элементов из пересечения А
и В. Зачем складывать?
Потому что, раз эти элементы являются частями обих множеств, то вычтя
последовательно А и В множества, мы как бы вычли эти элементы 2 раза. А
нам надо посчитать и их тоже.

Это и является принципов включения исключения - когда нам приходится
сначала исключать пересечение, а затем включать его.

*** Задача
Сколько целых чисел от 1 до 100 не делится ни на два, ни на три, ни на
пять?

**** Рассуждение
Это задача на принцип включения исключения. Распишем ее в нужной
терминологии
Итак, у нас есть множество Х - все числа от 1 до 100. Есть три множества:
А - это числа, которые делятся на 2
В - это числа, которые делятся на 3
С - делятся на  5

Нам нужно найти дополнение для этих трех множеств - т.е. числа, которые
входят в множество Х - являются числами от 0 до 100 - и при этом не
входят ни в одно из этих трех множеств.

Следовательно, нужно посчитать, сколько чисел делится на 2, 3 и 5,
т.е. вспомнить принципы делимости. При этом у заданных множеств могут
быть пересечеия - например, число делится на 2, 3 и 5 одновременно.

- В мнжество А попадают все четные числа - их будет ровно 50
- В множество В попадут 33 числа - просто делим 99 на 3.
- В множество C попадут 20 чисел.
- В пересечение А и В попадет 16 чисел - делим 96 на 6. Делим именно на 6,
потому что это минимальное число, которое делится на 2
и 3. Следовательно, нужно дальше каждый раз прибавлять 6 к числу, чтоб
получить следующее число, которое делится на 2 и 3. А 96 - это
максимальное число из 100, которое длится на 6.
- В пересечение А и С попадет 10 чисел - делим 100 на 10 (минимальное
  число, которое делится на 2 и 5)
- В пересечение B и С попадет 6 чисел - делим 90 на 15.
- В пересечение А, B, C попадет только 3 числа.

Теперь просто по формула включения исключений для 3х множеств считаем:
100 - 50 - 30 - 20 + 16 + 10 + 6 - 3 = 26.

**** Формула включния исключений для 3х множеств

|X| - |( A + B + C)|+ |А n B| + |B n C| + |A n C| - |A n B n C|
Эта формула позволяет узнать, сколько элементов в множесве Х, которые не
входят в множества А, B или С.

Почему формула выглядит именно так?

Разбираемся.
Мы вычли из X множества А, B и С. Мы знаем, что у нас есть элементы,
которе входят и в А, и в В. Когда мы вычли оба множества из множества Х,
то получается, что мы вычли такие элементы дважды. То же самое произошло
с элементами, которые находятся в пересечении множеств В и С, С и А.

Поэтому мы прибавляем все эти пересечения |А n B| + |B n C| + |A n C|
Так получается мы нейтрализуем "двойное" вычитание этих элементов.

Но есть элементы, которые входят во все три множества. Что получается? Мы
их три раза вычли, а потом 3 раза прибавили - потому что раз элементы
входят в пересечение всех трех множеств, то они будут входит и в
пересечение любых двух множеств среди наших А, В и С. Получается, что мы
как будто от них и не избавлялись.

Поэтому нужно вычесть их еще раз и только их. Поэтому финальным шагом мы
вычитаем |A n B n C|.

*** TODO Задача

Переплётчик должен переплести 12 различных книг в красный, синий и
коричневый цвета. Сколько имеется способов это сделать, если в каждый из
трех цветов должна быть переплетена хотя бы одна книга?

** Принцип Дирихле

По-другому этот принцип назывется принципом голубей и клеток.
Предположим, у нас имеется n ящиков и k предметов и при этом n строго
меньше k.
Тогда как бы мы не рассаживали предметы по ящикам, будет хотя бы 1 ящик,
в котором будет 2 или более предметов.

Принцип кажется очевидным. Но он может использоваться для решения
подзадач в более сложных задачах.

Допустим, дано n + 1 чисел, и нам нужно доказать, что хотя бы 2 числа из
этого набора имеют одинаковый остаток при делении на n. Т.е. мы говорим,
что a = n * q + r, где r - это какой-то остаток и он строго меньше
n. Если последовательно проделать так для всех чисел из первого набора,
то мы полчим новый набор чисел - набор остатков от деления. И кол-во
элементов в этом наборе будет меньше, чем кол-во элементов в исходном
наборе чисел. И по принципу Дирихле получается, что у нас будет хотя бы 1
число из второго набора, которому подходят хотя бы 2 числа из первого.

*** Задача
В ящике лежат десять белых и двенадцать черных носков. Какое минимальное
количество носков нужно вытащить, чтобы на выходе гарантированно получить
пару носков одинакового цвета?

**** Рассуждение

Это задача на принцип Дирихле. У нас есть k предметов - это наши
носки. Допустим, у нас есть 2 ящика: черный и белый, куда мы будем
раскладывать эти носки.

Ключевое в задаче - это "не вытащить одинаковые носки один за другим",
чтоб "в ящике оказалась пара носков одинакового цвета". По принципу
Дирихле мы знаем, что если у нас n ящиков и k предметов, то как только мы
разложим предметов в ящики больше, чем самих ящиков, то получится, что у
нас в каком-то ящике больше 1 элемента.

Раз 1 нас два "ящика" - 2 возможных  цвета - то как только мы вытащим 3
носка, то хотя бы в одном из ящиков у нас будет повторение, т.е. мы
получим пару носков с одинаковым цветом.

*** Задача
Какое максимальное количество королей можно поместить на шахматную доску
(стандартного размера, 8 × 8) так, чтобы эти короли не били друг друга?

**** Рассуждение
Опять рассматриваем задачу в терминах ящиков и предметов. По принципу
Дерихле у нас предметов должно быть строго больше, чем ящиков. Очевидно,
что клеток на шахматной доске будет явно больше, чем королей. Поэтому
считаем, что клетки шахматной доски - это предметы, а "ящики" - это
короли.

Если нарисовать на бумажке, то очевидно, что можно расставить максимум 16
королей.

Как посчитать это с помошью принципа Дирихле?

*** Задача
Сколько людей нужно выбрать из группы, состоящей из двадцати супружеских
пар, чтобы в выборку гарантированно вошла хотя бы одна супружеская пара?

**** Рассуждение
Задача похожа на первую, с носками. У нас есть 20 супружеских пар,
которые состоят из 40 человек. Таким образом, нам надо выбрать 21
человека, чтоб гарантированно получилась хотя бы 1 супружеская пара.

*** Задача
Сколько человек должно находиться в комнате, чтобы по крайней мере у
троих из них день рождения гарантированно был в одном месяце?

**** Рассуждение
Опять думаем в терминах предметов и ящиков. Очевидно, что ящики - это
месяцы, а предметы - это люди.

У нас есть 12 ящиков. Если мы возьмем 13 чел в комнате, то хотя бы у
двоих из них будет день рождения в один месяц. Следовательно, если из
будет 25, то гарантированно у троих будет ДР в один месяц.

* Модели комбинаторных конфигураций

** Размещение
Это упорядоченный набор из k различных элементов из некоторого
множества различных n элементов.

Т.е. есть множество (1 2 3 4 5), и есть набор из этого множества
(1 2 3) (2 3 4) (3 4 5). При этом размещение учитывает порядок,
в котором идут элементы. Т.е. (1 2 3) и (3 2 1) с т.з. размещения -
это разные наборы,хотя в них одни и те же элементы.

*** Формула для нахождения размещений БЕЗ повторений
Т.е. в каждом отдельном размещении нет повторяющихся элементов.
    n!
   ----
  (n-k)!

Процедура для этой формулы:
#+BEGIN_SRC lisp
  (defun factorial (n)
    (if (= n 0)
        1
        (* n (factorial (- n 1)))))

  (defun no-rep-placements (n k)
    (let* ((numerator (factorial n))
           (diff-fact (factorial (- n k))))
      (/ numerator diff-fact)))
#+END_SRC

При ~k = n~ количество размещений равно количеству перестановок
порядка n, т.е. n!.Т.е. если у меня множество из 5 элементов и нужно,
чтоб в каждом размещении было 5 элементов, то кол-во размещений = 5!

*** Формула для нахождения размещений C повторениями
Т.е. в каждом отдельном размещении есть повторяющиеся элементы.
Высчитывается как n^k. Т.е. если в множестве 4 элемента и мы хотим
получить размещения с повторяющимися элементами по 3 элемента в
каждом, то высчитывать будем как 4^3.

** Сочетание
https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D1%87%D0%B5%D1%82%D0%B0%D0%BD%D0%B8%D0%B5

Это из n по k набор элементов, выбранных из данных n элементов.
Наборы, отличающиеся только порядком следования элементов (но
не составом), считаются одинаковыми, этим сочетания
отличаются от размещений. Т.е. с т.з. сочетания (1 2 3) и (3 2 1) -
это одно и то же.

*** Формула для нахождения сочетаний БЕЗ повторений
Т.е. в каждом отдельном сочетании элементы не повторяются.

Число сочетаний из n по k равно биномиальному коэффициенту, т.е.
(n)     n!
    =  ----
(k)   k!(n-k)!

Предположим, у нас 5 элементов в множестве. 5 - это n, и мы хотим
выяснить кол-во сочетаний с неповторяющимися элементами по 2 элемента
в каждом для этого множества:
По форрмуле получается 5! / 2!(5-2)! = 120 / 2 * 6 = 10.

Про биноминальный коэффициент см. здесь:
https://ru.wikipedia.org/wiki/%D0%91%D0%B8%D0%BD%D0%BE%D0%BC%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D1%8D%D1%84%D1%84%D0%B8%D1%86%D0%B8%D0%B5%D0%BD%D1%82

Пишем процедуру для этой формулы:

#+BEGIN_SRC lisp
  (defun factorial (n)
    (if (= n 0)
        1
        (* n (factorial (- n 1)))))

  (defun no-rep-combin (n k)
    (let* ((numerator (factorial n))
           (k-fact (factorial k))
           (diff-fact (factorial (- n k)))
           (denumerator (* k-fact diff-fact)))
      (/ numerator denumerator)))
#+END_SRC

*** Формула для нахождения сочетаний С повторениями
(n + k - 1)!
-----------
 k!(n-1)!

Запрограммируем это:
#+BEGIN_SRC lisp
  (defun factorial (n)
    (if (= n 0)
        1
        (* n (factorial (- n 1)))))

  (defun rep-combin (n k)
    (let* ((numerator (factorial (- (+ n k) 1)))
           (k-fact (factorial k))
           (diff-fact (factorial (- n 1)))
           (denumerator (* k-fact diff-fact)))
      (/ numerator denumerator)))

  (rep-combin (* 9 9) 15)
#+END_SRC

** Перестановка
Это упорядоченный набор без повторений. Обычно он рассматривается как
биекция - т.е. соответствие одного множества другому, где каждый
элемент одного множества соответствует каждому элементу другого
множества.

Т.е. если у нас есть множество (1 2 3 4 5), то его переставнока - это
(5 4 3 2 1), поскольку каждому элементу соответствует каждый элемент,
а вот (3 2 1) уже не будет перестановкой, поскольку тут не установить
соответствие каждого элемента с каждым.

*** Формула
Число всех перестановок из n элементов равно числу размещений из n
по n, то есть факториалу.

Т.е. если у нас в множестве 3 элемента, то кол-во перестановок в них
= 3! = 6.

** Композиция
Это разложени числа на его слагаемые. Т.е. 5 мы представляем как
4 + 1, 2 + 3 и т.д.

Кол-во композиций считается как 2^(n-1), где n - величина, которую
надо разложить.

В композиции важен порядок следоваия элементов.
Поэтому 2 + 3 и 3 + 2 - это не одно и то же с т.зэ композиции.

** Разбиение
Это то же самое, что композиция, но порядок элементов неважен,
поэтому 2 + 3 и 3 + 2 с т.з. разбиения это одно и то же.

https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B7%D0%B1%D0%B8%D0%B5%D0%BD%D0%B8%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%B0

* Урновые схемы
Предположим, есть урна/ящик с некоторыми разичимыми предметами. Нам нужно
подсчитать, сколькими способами выбрать k предметов из урны. Может быть
вариант, когда мы достали предмет из урны, посчитали его и не положили
обратно, а могут быть варианты, когда мы предмет положили обратно в
урну.

Таким образом, у нас могут быть выборки без повторений и с
повторениями. Так же нам может быть важен порядок, а может быть не
важен.

Вот эти 4 фактора:
- порядок важен
- порядок неважен
- выборка с повторениями
- выборка без повторений

определяют, какие формулы использовать.

Схема рисуется в виде таблички.

* Задачи со степика

*** TODO Задача на сочетания
Сколько существует шестизначных чисел, сумма цифр которых не превосходит
47?

**** Рассуждение
Во-первых, суть в том, что нам нужно число, чьи цифры дают в сумме 47 -
т.е., например, число 999 992 - его цифры дают в сумме 47. И, кстати, это
максимальное шестизначное число, чьи цифры в сумме не превосходят 47.

Воспользуемся подсказкой.  Пойдем от обратного: посчитаем, сколько чисел
дают в сумме 48 или больше. Минимальное такое число - это 888 888. Т.е. нам
понадобилось отнять по единице от каждого разряда 999 999. Следовательно,
чтоб посчитать все числа, сумма которых равна 48 и больше, надо вычесть
6 или меньше единиц из любых разрядов числа 999 999. Так, например, у нас получатся
числа вроде 999 993, 988 887, 999 998 и т.д.


*** TODO Задача

Сколько существует бинарных (т.е. состоящих из цифр 0 и 1 ) строк длины
n, содержащих k единиц, в которых никакие две единицы не стоят рядом?
Решите задачу в общем случае, а в качестве ответа введите количество
таких строк для n = 42 и k = 7.

**** Рассуждение
Упростим задачу. У нас есть n элементов и нам нужно построить из них n
сочетаний - т.е. переставить все эти элементы.


101

10010
10100
10001
00101
01001

*** Задача на перестановки
Сколько чисел, меньших миллиона, можно записать с помощью цифр 8 и/или 9?

**** Рассуждение
Раз у нас числа меньше миллиона, то получется, что в числе может быть
максимум 6 разрядов, т.е. максимальное число у нас 999 999, сдедовательно
у нас максимум 6-элементное множество.

Разобьем его на 6 множеств и посчитаем перестановки для каждого
множества, а затем сложим их вместе.

В случае, если у меня один разряд в числе, то есть всего два возможных
числа, которые я могу составить с помщью заявленных цифр - 8 и 9.

В случае, если у меня 2 разряда, то получается, у меня n^k вариантов
перестановок - т.е. 4.

Если 3 разряда, то 8 вариантов и так далее. То есть мы число 2 возвозим в
степень k - в нашем случае это k - это кол-во разрядов в числе.
Таким образом получается, что
(+ (expt 2 1) (expt 2 2) (expt 2 3) (expt 2 4) (expt 2 5) (expt 2 6)) = 126

*** Задача на перестановки (размещения)

На перекрестке имеется 6 светофоров. Сколько существует различных
состояний этих светофоров, если каждый из них независимо от других имеет
три возможных состояния — горит красный, горит желтый или горит зеленый?


**** Рассуждение

Несмотря на кривую формулировку, в которой указаны "различные состояния",
по ходу решения выяснилось, что если, например, красным горят светофоры 1 2 3 4, а
желтым горят светофоры 5 6, а потом светофоры 1 2 4 5 горят красным, а
желтым горят 3 и 6, то такие два состояния считают различными, хотя в них
обоих четыре светофора горят красным, а оставшиеся два - желтым.

Поэтому получается, что задача допускает повторения в состояниях,
следовательно, нам нужна формула перестановок с повторениями - это
n^k. Где n - это кол-во цветов, а k - кол-во светофоров.

Получается ответ 729.

*** Задача на перестановки
Сколько существует шестизначных чисел, все цифры которых имеют одинаковую
четность?
Например, в числе 222 222 все цифры четные.

**** Рассуждение

Итак, у нас получается два набора шестизначных чисел - в одних все цифры
должны быть четные, в других - нечетные. При этом цифры, очевидно, могут
повторяться.

У нас получается 5 нечетных цифр: 1 3 5 7 9
И пять четных: 0 2 4 6 8

При этом есть загвоздка, что ноль, очевидно, не может быть ведущим в
числе.

Итак, чисел с нечетными цифрами может быть 5^6 степени. Потому что 5 цифр
и 6 возможных перестановок - у нас же шестизнаные числа.

Теперь считаем для четных: для первого разряда у нас вожны только 4
варианта - ноль не может быть ведущим. А вот для остальных пяти доступны
все 5 вариантов. Получается (expt 5 5) * 4 - потому что для каждого из 4х
вариантов первого разряда у нас могут быть все возможные варианты
остальных разрядов.

(+ (* 4 (expt 5 5)) (expt 5 6)) = 28125

*** Задача на размещения
Сколько существует трехзначных чисел в пятеричной системе счисления, в
которых все три цифры различны?

**** Рассуждение
Если у нас пятеричная система счисления, то в ней допустимы числа от 0
до 4.

Следовательно, нам фактически говорят найти все трехзначные числа,
состоящие из цифр от 0 до 4, где все цифры различны. При этом мы знаем,
что ноль не может быть ведущим.

Получается, что для первой цифры у нас есть 4 варианта (мы не учитываем
0), для второй - тоже 4 варианта (потому что одну цифру уже использовали,
но теперь можем использовать ноль), для третьей - 3 варианта (потому что
2 цифры из 5 точно испльзованы).

Получается (* 4 4 3) = 48 чисел.

*** Задача на размещения
Cколько существует восьмизначных чисел в пятеричной системе счисления, в
которых все цифры различны?

**** Рассуждение
Здесь все очевидно. В пятиричной системе счисления только 5 цифр: от 0 до
4 включительно. А у нас восьмизначное число - следовательно, какие-то
цифры точно будут повторяться.

Ответ: 0

*** Задача на размещения (перестановки)
В алфавите племени Бум-Бум всего шесть букв. Словом у них называется
любая последовательность из шести букв, в которой есть хотя бы две
одинаковые буквы. Сколько слов в языке Бум-Бум?

**** Рассуждение
Итак, это задача на перестановки с повторениями. При этом сложность
состоит в том, что в слове этого племени ~обязательно~ должны быть
повторяющиеся буквы.

Посчитать это просто. Сначала считаем все перестановки с повторениями,
потом - без повторений. Вычтя кол-во перестановок без повторений из
кол-ва перестановок с повторениями, мы получим только перестановки с
повторениями.

В алфавите и в слове одинаковое количество букв. Следовательно, кол-во
перестановок с повторениями - это 6^6. В то время как количество без
повторений - это 6!
Получается (- (expt 6 6 ) (factorial 6)) = 45936

*** Задача на размещения (перестановки)
Ребенок раскладывает в ряд разноцветные карточки с буквами "А", "А", "А",
"А", "А", "Е", "Е", "Г", "Л", "М", "М", "П", "П", "Р", "Т", "Т". Во
скольких вариантах получится слово "ТЕЛЕГАММААППАРАТ"?

**** Рассуждение
У нас есть 5 букв "А", 2 буквы "Е", 1 буква "Г",  1 буква "Л", 2 буквы
"М", 2 буквы "П", 1 "Р" и две "Т".

*** TODO Задача на размещения (перестановки)
Нужно сгенерировать все возможные k-перестановки n-элементов без
повторений.

Формат входные данные:
Два числа n и k через пробел. Для них гарантированно выполняется условие:
0 < k ≤ n.

Формат выходных данных:
Необходимое число лексикографически упорядоченных строк, в каждой из
которых содержится k чисел от 0 до n-1, разделенных пробелом.

*** TODO Задача
Сосчитать количество способов раскладки k неразличимых предметов по n
различимым ящикам при условии, что в каждом ящике должен находиться
как минимум один предмет. Решение записать в виде явной функции от n
и k.

**** TODO Рассуждение
см "теорию шаров и перегородок"
https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D1%88%D0%B0%D1%80%D0%BE%D0%B2_%D0%B8_%D0%BF%D0%B5%D1%80%D0%B5%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%BE%D0%BA

В ящике должен быть 1 и более предметов. Это значит, что нужно из
n-элементного множества найти k-мультимножество.

Считаем, что k >= n.
Если у нас равное вол-во ящиков и предметов, то у нас будет n!
способов разложить предметов по ящикам. Но у нас может быть больше
предметов, чем ящиков.

Тогда сначала раскладываем предметы так, чтоб получить по предмету в
каждом ящике.

*** Задача
В купе поезда едет 6 человек. Поезд делает 5 остановок. Сколькими
способами пассажиры могут распределиться между этими остановками?
Личности пассажиров нам не известны, мы их не различаем.

**** Рассуждение
У нас k неразичимых человек, которые нужно разложить по n  различимым
остановкам. Нет ограничения, что на каждой остановке должен выйти хотя бы
1 человек. То есть они могут все выйти на первой остановке, например.

И тогда это становится задача на сочетания с повторениями.
ФОрмулу можно посмотреть в разделе "сочетания" в этом конспекте.
Ответ: 201

*** Задача на размещения с повторениями
Трое мужчин и две женщины выбирают себе место работы (все люди считаются
различимыми). В городе имеются три фирмы, в которых требуются только
мужчины, две — в которых требуются только женщины, и две — в которых
берут и мужчин, и женщин. Сколькими способами они могут выбрать себе
место работы?

**** Рассуждение

Получается, что у нас 2 различимые женщины могут быть распределены между
4 различимыми фирмами. И 3 различимых мужчин могут быть распределены
между пятью разлимыми фирмами. При этом не обязательно, что каждая фирма
ищет только 1 человека: все мужчины могут уйти в однй фирму, например.

Значит, это задача на размещения с повторениями - потому что у нас и
люди, и фирмы различны.  Надо высчитать возможные размещения для мужчин и
женщин, а затем перемножить их друг с другом.

(* (expt 4 2) (expt 5 3))

*** Задача
Из группы, состоящей из 7 мужчин и 4 женщин, надо выбрать 6 человек так,
чтобы среди них было не менее 2 женщин. Сколькими способами это может
быть сделано?

**** Рассуждение

Представим себе, сколько способов сочетать:
- 3 мужчин и 3 женщин
- 4 мужчин и 2 женщин
- 4 женщин и 2 мужчин

И затем все перемножить. При этом мы считаем, что сочетания без
повторений.

Получается: (+ (* (no-rep-combin 7 3) (no-rep-combin 4 3))
               (* (no-rep-combin 7 4) (no-rep-combin 4 2))
               (* (no-rep-combin 4 4) (no-rep-combin 7 2))) = 371

* Задачи на разбор

Как правильно выбрать формулу см. здесь
https://www.matburo.ru/tv/Kombinatorics_MatBuro.pdf

** Задача 1
Раз в семестр студенты распределяются в проекты.
В этот раз в проект про распознавание марок автомобилей по фотографии
заявки подали 7 юношей и 4 девушки.
Проект набирает 6 студентов, среди которых должны быть хотя бы 2
девушки. Сколько способов выбрать студентов для этого проекта?

*** Разбор
Есть 2 множества юношей и девушек, в которых по 7 и 4 чел.
Нужно посчитать кол-во сочетаний с неповторяющимися элементами -
потому что нам все равно, в каком порядке будут ребята в проекте, а
так же потому, что в одной группе не может быть один и тот же человек
дважды.

Известно, что в размещении должно быть 6 элементов.
Соответственно возможны варианты: 3 + 3, 2 + 4 и 4 + 4 и внутри них
юноши и девушки могут быть размещены как угодно.

- Поэтому считаем размещения для каждого подмножества юношей и девушек
  отдельно: например, размещение 3 юношей из 7 возможных.

Используем процедуры, определенные для посика кол-ва сочетаний без
повторяющихся элементов:

#+BEGIN_SRC lisp
  ;; девушки
  (no-rep-combin 4 3)
  (no-rep-combin 4 2)
  (no-rep-combin 4 4)

  ;; парни
  (no-rep-combin 7 3)
  (no-rep-combin 7 2)
  (no-rep-combin 7 4)
#+END_SRC

- затем перемножаем полученные размещения парней и девушек друг с другом
  попарно так, чтоб суммарно кол-во k элементов было = 6.

#+BEGIN_SRC lisp
  (* (no-rep-combin 4 3)
     (no-rep-combin 7 3))

  (* (no-rep-combin 4 4)
     (no-rep-combin 7 2))

  (* (no-rep-combin 4 2)
     (no-rep-combin 7 4))
#+END_SRC

- и складываем полученные размещения, поскольку нам надо знать, сколько
  всего вариантов:

#+BEGIN_SRC lisp
  (+ (* (no-rep-combin 4 3)
        (no-rep-combin 7 3))
     (* (no-rep-combin 4 4)
        (no-rep-combin 7 2))
     (* (no-rep-combin 4 2)
        (no-rep-combin 7 4)))
#+END_SRC

** Задача 2

У Маши есть полное собрание энциклопедий, включающее 15 пронумерованных
томов, и полка, разделенная на 15 ячеек. Маша решила расставить
энциклопедии по этим ячейкам, руководствуясь следующими правилами:

- книги расставляются последовательно (начиная с первого тома, потом
  второй, затем третий и тд);

- первый том ставится в произвольную ячейку;

- каждый следующий том ставится в любую соседнюю ячейку с уже занятыми;
  в одной ячейке может находиться только одна книга.

Сколькими способами можно расставить тома энциклопедии? В ответе укажите
одно целое число.

*** Разбор не доделан

У нас есть:
- 15 неповторяющихся элементов

- они расставляются последовательно: т.е. комбинация (1 2 3 4) возможна,
  а (1 3 2 4) - нет

- каждый следующий том может быть расставлен только в соседнюю ячейку с
  уже занятыми - при этом вставляться он должен таким образом, чтоб не
  нарушать порядок томов.

- первый том будет поставлен в любую чейку - следовательно, если первый
  том поставили в третью ячейку, то у нас не влезет все 15 томов,
  поскольку первые 2 ячейки окажутся пустыми: мы не можем нарушать
  порядок томов.

  Убывающее кол-во томов намекает нам, что это может задача на формулу
  размещений, поскольку в ней убывающий факториал. И теперь к нему надо
  как-то приделать условие, согласно которому, у нас тома могут идти
  строго подряд.

** Задача 3

На родительское собрание в школу пришли 6 супружеских пар. Классному
руководителю для организации родительского комитета необходимо выбрать из
них ровно 3 человека. Комитет не должен включать пару, состоящую в
браке. Сколькими способами можно организовать родительский комитет?

*** Разбор
- есть 3 множества по 2 элемента в каждом

- мы знаем, что из каждого множества можно взять только 1 элемент во
  время одного эксперимента

- элементы не повторяются

Итак, я думаю, что это задание на поиск сочетаний без повторений, потому
что:
- нет повторений
- порядок элементов неважен

Есть 3 варианта организации родительского комитета:
- 3 женщин
- 3 мужчин
- 2 женщины + 1 мужчина
- 2 мужчин + 1 женщина

Мы можем разделить пары на два множества: мужчин и женщин, в каждом
приходится по 6 чел.

Считаем кол-во вариантов, если комитет состоит только из мужчин или
только из женщин - если б мы искали комитет, в котором состоит ровно 6
чел и при этом должно быть 3 мужчин и 3 женщин, то размещения пришлось бы
не складывать, а умножать, как в задаче 1.
#+BEGIN_SRC lisp
  (+ (no-rep-combin 6 3)
     (no-rep-combin 6 3))
#+END_SRC

Теперь считаем варианты для:
- 2 женщины + 1 мужчина
- 2 мужчин + 1 женщина

В этом случае размещения придется сначала умножить, а потом сложить
полученные произведения, как в задаче 1.
#+BEGIN_SRC lisp
  (+ (* (no-rep-combin 6 1)
        (no-rep-combin 5 2))
     (* (no-rep-combin 6 1)
        (no-rep-combin 5 2)))
#+END_SRC

Теперь складываем это все:
#+BEGIN_SRC lisp
  (+ (* 2 (* (no-rep-combin 6 1)
             (no-rep-combin 5 2)))
     (* 2 (no-rep-combin 6 3)))
#+END_SRC

** Задача 4

В стране 20 городов. Правительство выделило деньги на строительство 187
дорог. Каждая дорога соединяет два разных города и не проходит через другие
города.  Между любыми двумя городами не может быть больше
одной дороги. Сколько существует способов проложить дороги?

*** Разбор

Итак:
- у нас нет повторений - каждый город уникальный, а между любыми двумя
  городами может быть только 1 дорога
- порядок неважен

Скорее всего, это опять задача на сочетания. Каждый город может быть
соединен с любым из других 19 городов. В этом случае у нас получается,
что каждый город соединен с каждым двумя дорогами. Так что делим
полученное число на 2. Это значит, что может быть всего
190 дорог для всех городов. Но у нас только 187. Значит, нужно просто
выбрать сочетания для 187 из 190 дорог.

Получается 1125180:
#+BEGIN_SRC lisp
  (no-rep-combin 190 187)
#+END_SRC

** Задача 5
Среди 126 студентов каждый имеет ровно трёх друзей (понятие «быть другом»
симметрично). Студенты строго упорядочены по рейтингу (студентов с равным
рейтингом нет). Будем говорить, что студент учится лучше своих друзей,
если он по рейтингу выше хотя бы двух из своих друзей. Какое максимальное
значение может принимать число студентов, которые учатся лучше своих друзей?

*** Разбор не доделан
- нам важен порядок
- и нет повторений - потому что нет двух одинаковых рейтингов или
  студентов
- не нужно выбрать все n элементов

Следовательно, это задача на размещения без повторений.

У нас есть 126 студентов и мы их можем разбить по 4 человека - потому что
у каждого студента есть ровно 3 друга.  Студент, чтоб считаться лучшим,
должен учиться лучше минимум двух из них, т.е. так же он может считаться
лучшим, если учится лучше всех из своих друзей.

#+BEGIN_SRC lisp
  (no-rep-placements 126 4)
#+END_SRC

* Задачи из методички новосиб. техвуз
** Задача 6
Есть 3 железные дороги, идущие от Б до Н, и 4, идущие от Н до Т.
Сколькими способами можно выбрать дорогу от Б до Т через Н?

Итак, это задача на сочетания без повоторений, потому что:
- дороги и города уникальны
- порядок выбора дорог неважен

У нас есть 2 множества: дороги от Б до Н и дороги от Н до Т.
Представим это как множества (1 2 3) и (1 2 3 4)

Поскольку задачка маленькая, а мы неуверены в решении, то пробуем
посмотреть вручную все возможные способы добраться от Б до Т.

У нас будут следующие сочетания путей:
(1 1)
(1 2)
(1 3)
(1 4)

(2 1)
(2 2)
(2 3)
(2 4)

(3 1)
(3 2)
(3 3)
(3 4)

Вручную видно, что кол-во возмодных способов = 12.
Т.е. если использовать процедуры, написанные мной для вычисления
сочетаний, получится такое:

#+BEGIN_SRC lisp
  (* (no-rep-combi 4 1)
     (no-rep-combi 3 1))
#+END_SRC

Где n - это кол-во элементов в множествах - 3 или 4, а k - это кол-во
элементов в сочетании, которое мы хотим видеть из каждого множества за 1
эксперимент. Умножение используется поскольку нам нужны сочетания обоих
множеств.

** Задача 7

Сколькими способами можно разместить 12 гостей за столом?

Я думаю, что это задача на перестановки: надо выбрать все элементы, но
при этом порядок неважен. Поэтому ответ 12! = 479 001 600.

** Задача 8

В конкурсе красоты участвует 8 девушек. Сколькими способами можно между
ними распределить места, если 1 место = 1 девушка?

Задача как с гостями за столом. Ответ 8! = 40 320

** Задача 9

Сколькими способами может быть присуждена 1 и 2 место двум лицам из
группы в 9 человек?

Это задача на размещения без повторений:
- нет повторений
- надо выбрать не все n элементов - (иначе это была бы задача на
  распределение всех мест)
- порядок важен

Получается, что из 9 чел. каждый может претендовать на первую
премию. Потом 1 получает первое место и остается 8 чел, каждый из которых
может претендовать на второе место.

Т.е. у нас получается в первый раз n = 9, а k = 1, а во второй раз n = 8,
а k = 1. Если в каком-то размещении или сочетании надо сделать размещение
или сочетания по 1 элементу, то кол-во этих сочетний или размещений будет
= n элементов из исходного множества.

Следовательно, в этом задании можно выкинуть формулу и просто
переменожить 9 * 8 = 72

** Задача 10
Сколько трехзначных чисел можно образовать из цифр 1 2 3 5, если каждую
из тих цифр можно:

- испльзовать в числе 1 раз
- использовать в числе более 1 раза

1.
Это задача на размещения без повторений:
- нет повторений
- порядо цифр важен - т.е. 123 != 321

Получается, у нас множество из 4х цифр, для которых надо сгенерировать
сочетания по 3 элемента. Получается, что на первом месте может стоять 1
из 4х цифр, на втором - одна из трех и т.д. Задача похожа на предыдущую,
получаем: 4 * 3 * 2 = 24

2. Размещение с повторениями.
В данном случае ответ такой же. По формуле кол-во размещений находится
как n^k. Но получается, что у нас k = 1, а любое число в 1 степени - это
то же самое число.

** Задача 11
В купе поезда два противомоложных пятиместных дивана. Из 10 пассажиров 4
хотят ехать по ходу, 3 против хода и остальным все равно как
сидеть. Сколькими способами их можно рассладить?

Я думаю, что это задача на размещения без повторений.
Потому что:
- порядок сидящих пассажиров важен, они ж неоднородные
- нет повторений

Делим места на два множества: против хода и по ходу. Это значит, что
четверо могут сесть только на одни 5 мест, еще трое - строго на другие 5
мест, а трое, которым все равно, как ехать, на оставшиеся места после
того, как другие "сели". Т.е. получатся, что трое, которым все равно,
будут размещаться не на 5 местах или на 10, а на трех, потому что другие
заняты.
#+BEGIN_SRC lisp
  (* (no-rep-placements 5 4)
     (no-rep-placements 5 3)
     (no-rep-placements 3 3))
#+END_SRC

** Задача 12
Хор состоит из 20 певцов. Сколькими способами можно в течение трех дней
выбирать по 15 певцов так, чтобы каждый день были разные составы хора?

Итак, я думаю, что это задача на сочетания без повторений. Потому что:
- составы хора должны быть уникальны
- нужно выбрать не все n элементов
- порядок неважен: мне все равно, будет хор стоять как 1 2 3 4 5 или как
  5 2 3 4 1

Ответ: 3 726 037 653 024
#+BEGIN_SRC lisp
  (no-rep-combin 20 15)
  (* 15504 15503 15502)
#+END_SRC

** Задача 13
В меню столовой имеется 5 видов первых блюд и 3 вида вторых, а на десерт
всегда предлагается кофе или чай. Сколькими способами можно выбрать обед
так, чтоб:
- он состояил из 1 первого, 1 второго и 1 третьего блюда?
- он состояиз из двух неповторяющихся вторых блюд и одного третьего?

Это явно задача на неповторяющиеся сочетания.

Для задания 1 ответ 30.
#+BEGIN_SRC lisp
  (* (no-rep-combin 5 1)
     (no-rep-combin 3 1)
     (no-rep-combin 2 1))
#+END_SRC

Для задания 2 ответ 6.
#+BEGIN_SRC lisp
  (* (no-rep-combin 3 2)
     (no-rep-combin 2 1))
#+END_SRC

** Задача 14
Сколько чисел больше 100 можно записать с помощью цифр 0 2 4 6, чтоб ни в
одном числе цифра не повтрялась и ни ожно число не начиналось с нуля?

Это явно задача на размещеия без повторений: потому что ващен порядок в
числах. Нужно реализовать 2 ограничения: числа не должны быть больше 100
и не должны начинаться с нуля.

Итак, получается, что у нас возможны только двузначные числа - потому что
в 100 содержится два нуля, а по условию в числе не могут повторяться
цифры.
Так же получается, что цифры 2 4 6 могут стоять на обоих разрядах числа,
а ноль - только в младшем.

Ответ: 9, но я хз как считать это с применением формул.
#+BEGIN_SRC lisp
  20
  40
  60

  26
  24

  42
  46

  62
  64
#+END_SRC


** Задача 15
В классе 7 девочек и 11 мальчиков. Сколько способов рассадить их в
кабинете за 12 двухместных парт так, чтобы любая девочка обязательно
сидела за одной партой с мальчиком?

(Мальчики могут сидеть по двое или по одному, но на определенном месте за
партой). Ответ не должен содержать суммирование по параметру)

*** Разбор
Итак, в кабинете 12 двухместных парт, т.е. всего 24 места. Детей всего
18 - это значит, что если 14 детей (7 девочек и 7 мальчиков) будут сидеть
вместе, они займут 7 парт. У нас останется еще 4 парты на 4 мальчиков -
это значит, что в случае, если какие-то мальчики сядут за одну парту, то
одна парта окажется пустой.

Получается, что первуюдевочку можно рассадитьзалюбую из 12 парт, к нему
можно посадить первого из 11 мальчиков. И сделать это можно двумя
способами: один слева, другой справа или наоборот. При этом возможны
повторения: когда за двумя партами оба мальчика сидят слева, а обе
девочки справа - или наоборот.

Поэтому нужно учесть, что мы считаем размещения и с повторениями -
мальчик/девочка за партой или девочка/мальчик - и без повторений:
мальчики и девочки уникальны и не могут сидеть за двумя партами
одновременно.

#+BEGIN_SRC lisp
  (* (* 12 11 10 9 8 7 6 5)
     (expt 2 7)
     (* 4 3 2))
#+END_SRC

* Задачи с использованием кода

** Задача
Нужно сгенерировать все возможные k-сочетания из n элементов.

Формат входных данных:
Два числа k и n через пробел. Для них гарантированно выполняется условие:
0≤k≤n.

Формат выходных данных:
Необходимое число строк, в каждой из которых содержится k чисел из
диапазона от 0 до n-1 включительно, разделенных пробелом.

* Отображения
Отображение тождественно слову "функция" - т.е. соответствие между
элементами двух множеств.

Записиывается как f: X -> Y, а читается как "отображение множества X в
множество Y". Допустим, есть множество X (1 2 3 4) и множество Y
(1 4 9 16). Множество X отображается в множество Y как f(x) = x^2.

** Задача 14
Результаты опроса 1000 случайно отобранных молодых людей таковы:
- работают 811 чел.,
- учатся 518 чел.,
- работают и учатся одновременно 356 чел.,
- проживают в Петербурге 752 чел.,

Из Петербуржцев:
- работают 570 чел.,
- учатся 348 чел.,
- работают и учатся одновременно 297 чел.,

Определите, содержится ли в этой информации ошибка? Поясните свой ответ.

Итак, считаем. Всего есть 1000 человек.
Из них работает 811 чел, учистся 518 чел, а работает и учится - 356
чел.

Получается, что у нас есть 3 множества, где третье - это пересечение двух
других множеств. Посчитаем, сколько у нас народу находится только в
первом множестве - т.е. только работают, и только во втором множестве -
т.е. только учатся. Мы ожидаем, что если сложить тех, кто только учится с
теми, кто только работает и с теми, кто учится и работает, то получится
1000 чел.

#+BEGIN_SRC lisp
  (+ (- 811 356)
     (- 518 356)
     356)
#+END_SRC

Но получается 973 человека - кого-то не хватает.

Теперь считаем, что там с Петербуржцами. Мы знаем, что из 1000 чел 752
проживают в Петербурге. Значит, остальные 248 чел проживают в других
городах.

Значит, мы ожидаем, что те, кто не работает, не учится или не работае и
не учится в Питере должны образовывать оставшиеся 248 чел, которые
учатся, работают, работают и учатся в другом месте.

Сначала проверяем данные чисто по Питеру - дейтсвительно ли 3 множества
складываются в 752 человека.

#+BEGIN_SRC lisp
  (+ (- 570 297)
     (- 348 297)
     297)
#+END_SRC

Получается уже 621 чел - кого-то не хватает.

И можно было бы сказать, что информация неверна. Но есть еще неявно
заданное множество: это люди, которые не учатся, и не работают. Поэтому
раз кол-во учащихся и работающих меньше, чем суммарное количество
опрошенных, то информация верна.

* Свойства отображений

** Инъективное отображение
Это когда каждому элементу в множестве соответствует какой-то 1 элемент в
другом множестве. Пример, f(x) = x^3 - это пример инъективного
отображения. А f(x) = x^2 - нет, потому что -2 и 2 в квадрате дают одно и
то же число.

** Сюръективное отображение
Есть два множества X и Y: если в каждый элемент множества Y отображается
~хотя бы один~ элемент из множества X - это отображение
сюръективно. Т.е. это значит, что у нас несколько элементов из множества
X могут соответствовать одному элементу из множества Y. При этом в
множестве Y не может быть "не занятых" элементов.

Например, берем Х{0; 3} и Y {0 ; 9}, в качестве правила отображения
задаем f(x) = x^2. По правилу отображения получается, что f: X -> Y
сюръективно, потому что каждому элементу из Y cоответствует како-то
элемент из X. А если задать Y как {0 ; 10}, то отображение уже
несюръективно: у нас нет элемента в множестве X, который по заданному
правилу отображения отображался бы в элемент 10.

** Биективное отображение
Это когда отображение инъективно и сюръективно. То есть разные точки из
множества X переходят в ~разные~ точки из множетсва Y - свойство
инъекции, но при этом все точки Y соответсвутю каким-то точкам из X,
т.е. все точки из Y "заняты".

** Тождественное отображение
Функция, переводящая аргумент в себя - это значит, что каждому элементу в
множестве можно сопоставить другой элемент в этом же множестве по
какому-то признаку.

Это образцовое преобразование множество, оно точно есть у каждого
множества.

* Задачи из 9 класса
** Задача 1

Несколько стран в качестве символа своего государства решили использовать
флаг в виде 3-х горизонтальных полос одинаковых по ширине и цвету: синий,
красный и белый. Сколько стран могут испытать такую символику при
условии, что у каждой страны свой отличный от других флаг?

*** Рассуждение
Это задача на перестановки без повторений. Очевидно, что только 3! стран
могут получить отличные друг от друга флаги - т.е.  6.

** Задача 2
Сколько трехзначных чисел можно составить из цифр 1, 3, 5, 7, используя в
записи числа каждую из них не более одного раза?

*** Рассуждение
Это очевидно задача на размещения без повторений. Формулу можно
посмотреть в соответствующем разделе этого мана.

Ответ: 24.

** Задача 3

В урне лежат два белых и два черных шара. На ощупь их различить
невозможно. При вытаскивании белого шара его откладывают в сторону, если
вытащили черный шар, то его кладут обратно. Шары вытаскивают четыре раза подряд.

В скольких случаях вытащат все шары одинакового цвета?
В скольких случаях белые шары появятся раньше?

*** Рассуждение

Очевидно, что все одинаковые шары можно вытащить только в случае, если
они все черные. Два белых шара подряд раньше черных можно достать тоже в единственном
случае. Один белый шар можно достать первым в 50% случаев.

* Олимпиадные задачи из разных источников
** Задачи на перебор вариантов

*** TODO Задача 1
На шахматной доске 7×7 посчитайте количество всех квад-ратов, границы
которых проходят по границам клеток.

**** Рассуждеие
Если квадраты проходят по границам клеток, то у нас могут быть квадраты
только 2x2, 3x3, 4x4, 5x5, 6x6 клеток.


*** TODO Задача 2

Скуперфильд хочет выплатить наложенный на него штраф в 1000 фертингов
монетами в 7 и 13 фертингов. Сколькими способами он может это
сделать? Каким наименьшим количеством монет он может обойтись?

**** Рассуждение
Монета в 7 фертингов и в 13 фертингов в сумме дают 20 фертингов.
1000 / 20 = 50. А мы использовали по 2 монеты в каждой двадцатке,
следовательно нужно 100 монет, чтоб набрать 1000.



*** Задача 3

Четыре гостя при входе в ресторан отдали швейцару свои шляпы, а при
выходе получили их обратно. Невнимательный швейцар раздал шляпы
случайным образом.
Сколько существует вариантов, при которых каждый гость получил
чужую шляпу?

**** Рассуждение

У нас всего 4 гостя и каждый может получить любую шляпу ~кроме своей~.
Т.е. у каждого гостя выбор состоит максимум из 3х шляп.

Пронумеруем шляпы: 1 2 3 4.
Первый гость может взять любую из 4 шляп кроме первой. Он берет,
допустим, шляпу №3, осталось 3 шляпы.
Второй гость берет шляпу №1 - оосталось две шляпы.
Если осталось 2 шляпы на двоих гостей, то получается, что у каждого из
них есть только 1 вариант выбрать не свою шляпу.

Итого получается (* 3 3 1 1) = 9 вариантов.

*** Задача 4

На клетчатой бумаге нарисован квадрат размером 3×3 клеточки. Требуется
закрасить в этом квадрате три клеточки так, чтобы никакие две
закрашенные клеточки не имели общей стороны. Сколькими способами это можно
сделать? Два способа раскраски считаются одинаковыми, если один можно
получить из другого поворотом квадрата.

**** Рассуждение
Очевидно, что никакие 2 или более клеток не могут быть расположены
подряд по вертикали или горизонтали.
