* ИНтро

Шпаргалка про механизмы синхронизации на уровне ОС.

* Термины
** Активное ожидание

Поток/процесс крутится в цикле, ожидая определенного значения у какой-то
переменной и постоянно проверяя ее.
Рекомендуется избегать, поскльку это впустую тратит ресурсы.

** Спин-блокировка

Блокировка, использующая активное ожидание.

* Механизмы синхронизации, использующиеся сегодня

** Семафор

Это целочисленная переменная, которая показывает, сколько
процессов может получить доступ к ресурсу.

Над семафором можно совершить 2 операции:
- down
- up

~down~ проверяет значения семафора. Если оно больше нуля, то ~down~
уменьшает значение семафора на 1 и процесс входит в критическую
секцию. Если же значение семафора = 0, то процесс, вызвавший ~down~,
замирает в ожидании, когда значение семафора снова станет не нудевым.

~up~ проверят значение семафора и увеличивает его на единицу. Если в этот
момент есть процессы, которые ожидают освобождения семафора, система
выбирает один из них и запускает его. Значение семафора так и остается
нулевым, а количество ожидающих процессов уменьшается.

** Мьюеткс

Это частный случай семафора, когда значение семафора может быть только 0
или 1. Т.е. только 1 поток может входить в критическую секцию.
